name: Bug report
description: You've found a bug with registers.nvim.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Before you begin to fill out the form, make sure you have actually found a bug.
        If you're not sure then create a [discussion](https://github.com/tversteeg/registers.nvim/discussions) first.
        If you have questions or want help with registers.nvim, then also create a [discussion](https://github.com/tversteeg/registers.nvim/discussions).

  - type: dropdown
    id: platform-select
    attributes:
      label: Please select which platform you are using.
      options:
        - 'Linux'
        - 'Mac'
        - 'Windows'
    validations:
      required: false

  - type: dropdown
    id: regression-error
    attributes:
      label: Was this something which used to work for you, and then stopped?
      options:
        - 'It used to work, and then stopped'
        - 'I never saw this working'
    validations:
      required: true

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
    validations:
      required: true
